# Generated by Django 6.0 on 2025-12-10 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('code', models.CharField(choices=[('DIR', 'Dirección'), ('REC', 'Recepción'), ('LIM', 'Limpieza'), ('MAN', 'Mantenimiento'), ('RES', 'Restaurante')], max_length=3, verbose_name='Código')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Cargo')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar')),
                ('employee_number', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Número de empleado')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='Fecha de contratación')),
                ('is_available', models.BooleanField(default=True, help_text='Indica si el empleado está disponible para asignaciones', verbose_name='Disponible')),
                ('bio', models.TextField(blank=True, help_text='Información adicional del empleado', verbose_name='Biografía')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.department', verbose_name='Departamento')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
