# Generated by Django 6.0 on 2025-12-11 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='color',
            field=models.CharField(choices=[('#3B82F6', 'Azul'), ('#10B981', 'Verde'), ('#F59E0B', 'Amarillo'), ('#EF4444', 'Rojo'), ('#8B5CF6', 'Púrpura')], default='#3B82F6', max_length=7, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(choices=[('DIR', 'Dirección'), ('REC', 'Recepción'), ('LIM', 'Limpieza'), ('MAN', 'Mantenimiento'), ('RES', 'Restaurante')], max_length=3, unique=True, verbose_name='Código'),
        ),
    ]
