# Generated by Django 6.0 on 2025-12-12 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_department_color_alter_department_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(max_length=3, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='department',
            name='color',
            field=models.CharField(choices=[('#3B82F6', 'Azul'), ('#10B981', 'Verde'), ('#F59E0B', 'Amarillo'), ('#EF4444', 'Rojo'), ('#8B5CF6', 'Púrpura'), ('#27F5E4', 'Cyan'), ('#F59C27', 'Orange'), ('#D44E96', 'Pink'), ('#693A10', 'Brown')], default='#3B82F6', max_length=7, verbose_name='Color'),
        ),
    ]
