# Generated by Django 6.0 on 2025-12-12 18:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_department_code_alter_department_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(help_text='Código de 3 letras mayúsculas (ej: DIR, REC, LIM)', max_length=3, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_code', message='El código debe tener exactamente 3 letras mayúsculas', regex='^[A-Z]{3}$')], verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='department',
            name='color',
            field=models.CharField(choices=[('#3B82F6', 'Azul'), ('#10B981', 'Verde'), ('#F59E0B', 'Amarillo'), ('#EF4444', 'Rojo'), ('#8B5CF6', 'Púrpura'), ('#EC4899', 'Rosa'), ('#F97316', 'Naranja'), ('#06B6D4', 'Cyan'), ('#6366F1', 'Índigo'), ('#84CC16', 'Lima'), ('#059669', 'Esmeralda'), ('#6B7280', 'Gris')], default='#3B82F6', max_length=7, verbose_name='Color'),
        ),
    ]
