# Generated by Django 6.0 on 2025-12-14 11:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_department_code_alter_department_color'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('vacation', 'Vacaciones'), ('sick', 'Baja médica'), ('personal', 'Asunto personal'), ('unpaid', 'Sin sueldo'), ('other', 'Otro')], max_length=20, verbose_name='Tipo de permiso')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de fin')),
                ('reason', models.TextField(verbose_name='Motivo')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Estado')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de aprobación')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Motivo de rechazo')),
                ('attachment', models.FileField(blank=True, help_text='Justificante médico u otro documento', null=True, upload_to='leaves/', verbose_name='Documento adjunto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de solicitud')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='users.userprofile', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Hora de entrada')),
                ('check_out', models.DateTimeField(blank=True, null=True, verbose_name='Hora de salida')),
                ('status', models.CharField(choices=[('present', 'Presente'), ('late', 'Tarde'), ('absent', 'Ausente'), ('half_day', 'Medio día')], default='present', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, help_text='Observaciones sobre el fichaje', verbose_name='Notas')),
                ('check_in_location', models.CharField(blank=True, help_text='Ubicación GPS o lugar de fichaje', max_length=200, verbose_name='Ubicación entrada')),
                ('check_out_location', models.CharField(blank=True, max_length=200, verbose_name='Ubicación salida')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='users.userprofile', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'ordering': ['-check_in'],
                'indexes': [models.Index(fields=['employee', '-check_in'], name='users_atten_employe_fcd0ef_idx'), models.Index(fields=['check_in'], name='users_atten_check_i_6995a2_idx')],
            },
        ),
    ]
