# Generated by Django 6.0 on 2026-02-09 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0004_alter_employee_options_alter_employee_bio_and_more"),
        ("leave", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="leave",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Leave",
                "verbose_name_plural": "Leaves",
            },
        ),
        migrations.AlterField(
            model_name="leave",
            name="approved_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Approval date"
            ),
        ),
        migrations.AlterField(
            model_name="leave",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_leaves",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Approved by",
            ),
        ),
        migrations.AlterField(
            model_name="leave",
            name="attachment",
            field=models.FileField(
                blank=True,
                help_text="Any document",
                null=True,
                upload_to="leaves/",
                verbose_name="Attached",
            ),
        ),
        migrations.AlterField(
            model_name="leave",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="leave",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leaves",
                to="employees.employee",
                verbose_name="Employee",
            ),
        ),
        migrations.AlterField(
            model_name="leave",
            name="end_date",
            field=models.DateField(verbose_name="End date"),
        ),
        migrations.AlterField(
            model_name="leave",
            name="leave_type",
            field=models.CharField(
                choices=[
                    ("vacation", "Vacation"),
                    ("sick", "Sick"),
                    ("personal", "Personal"),
                    ("unpaid", "Unpaid"),
                    ("other", "Other"),
                ],
                max_length=20,
                verbose_name="Tipo de permiso",
            ),
        ),
        migrations.AlterField(
            model_name="leave",
            name="reason",
            field=models.TextField(verbose_name="Reason"),
        ),
        migrations.AlterField(
            model_name="leave",
            name="rejection_reason",
            field=models.TextField(blank=True, verbose_name="Rejection reason"),
        ),
        migrations.AlterField(
            model_name="leave",
            name="start_date",
            field=models.DateField(verbose_name="Start date"),
        ),
        migrations.AlterField(
            model_name="leave",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="leave",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Last update"),
        ),
    ]
