# Generated by Django 6.0 on 2026-02-15 17:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0005_alter_employee_role"),
        ("leave", "0002_alter_leave_options_alter_leave_approved_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="leave",
            name="attachment",
            field=models.FileField(
                blank=True,
                help_text="Supporting document",
                null=True,
                upload_to="leaves/",
                verbose_name="Attachment",
            ),
        ),
        migrations.AlterField(
            model_name="leave",
            name="leave_type",
            field=models.CharField(
                choices=[
                    ("vacation", "Vacation"),
                    ("sick", "Sick"),
                    ("personal", "Personal"),
                    ("unpaid", "Unpaid"),
                    ("other", "Other"),
                ],
                max_length=20,
                verbose_name="Leave_type",
            ),
        ),
        migrations.AlterField(
            model_name="leave",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Last updated"),
        ),
        migrations.AddConstraint(
            model_name="leave",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_date__gte", models.F("start_date"))),
                name="valid_leave_date_range",
            ),
        ),
    ]
