# Generated by Django 6.0 on 2025-12-22 19:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Hora de entrada')),
                ('check_out', models.DateTimeField(blank=True, null=True, verbose_name='Hora de salida')),
                ('status', models.CharField(choices=[('present', 'Presente'), ('late', 'Tarde'), ('absent', 'Ausente'), ('half_day', 'Medio día')], default='present', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, help_text='Observaciones sobre el fichaje', verbose_name='Notas')),
                ('check_in_location', models.CharField(blank=True, help_text='Ubicación GPS o lugar de fichaje', max_length=200, verbose_name='Ubicación entrada')),
                ('check_out_location', models.CharField(blank=True, max_length=200, verbose_name='Ubicación salida')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='employees.employee', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'ordering': ['-check_in'],
                'indexes': [models.Index(fields=['employee', '-check_in'], name='attendance__employe_eccccc_idx'), models.Index(fields=['check_in'], name='attendance__check_i_e94952_idx')],
            },
        ),
    ]
