# Generated by Django 6.0 on 2026-02-09 10:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendance",
            name="check_in_location",
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="check_out_location",
        ),
    ]
