# Generated by Django 6.0 on 2026-02-09 15:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0002_remove_attendance_check_in_location_and_more"),
        ("employees", "0004_alter_employee_options_alter_employee_bio_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attendance",
            options={
                "ordering": ["-check_in"],
                "verbose_name": "Attendance",
                "verbose_name_plural": "Attendances",
            },
        ),
        migrations.AlterField(
            model_name="attendance",
            name="check_in",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Check-in time"
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="check_out",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Check-out time"
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created_at"),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendances",
                to="employees.employee",
                verbose_name="Employee",
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Observations about the attendance record",
                verbose_name="Notes",
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="status",
            field=models.CharField(
                choices=[
                    ("present", "Present"),
                    ("late", "Late"),
                    ("absent", "Absent"),
                    ("half_day", "Half day"),
                ],
                default="present",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AddConstraint(
            model_name="attendance",
            constraint=models.UniqueConstraint(
                condition=models.Q(("check_out__isnull", True)),
                fields=("employee",),
                name="unique_open_attendance_per_employee",
            ),
        ),
        migrations.AddConstraint(
            model_name="attendance",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("check_out__gte", models.F("check_in")),
                    ("check_out__isnull", True),
                    _connector="OR",
                ),
                name="check_out_after_check_in",
            ),
        ),
    ]
