# Generated by Django 6.0 on 2026-02-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "attendance",
            "0003_alter_attendance_options_alter_attendance_check_in_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendance",
            name="notes",
        ),
        migrations.AlterField(
            model_name="attendance",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
    ]
