# Generated by Django 6.0 on 2025-12-22 19:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('color', models.CharField(choices=[('#3B82F6', 'Azul'), ('#10B981', 'Verde'), ('#F59E0B', 'Amarillo'), ('#EF4444', 'Rojo'), ('#8B5CF6', 'Púrpura'), ('#EC4899', 'Rosa'), ('#F97316', 'Naranja'), ('#06B6D4', 'Cyan'), ('#6366F1', 'Índigo'), ('#84CC16', 'Lima'), ('#059669', 'Esmeralda'), ('#6B7280', 'Gris')], default='#3B82F6', max_length=7, verbose_name='Color')),
                ('code', models.CharField(help_text='Código de 3 letras mayúsculas (ej: DIR, REC, LIM)', max_length=3, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_code', message='El código debe tener exactamente 3 letras mayúsculas', regex='^[A-Z]{3}$')], verbose_name='Código')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('director', 'Director/a'), ('jefe_recepcion', 'Jefe/a de Recepción'), ('recepcionista', 'Recepcionista'), ('jefe_limpieza', 'Jefe/a de Limpieza'), ('camarero_piso', 'Camarero/a de Piso'), ('jefe_mantenimiento', 'Jefe/a de Mantenimiento'), ('mantenimiento', 'Personal de Mantenimiento'), ('rrhh', 'Recursos Humanos')], default='camarero_piso', help_text='Rol del empleado en el hotel', max_length=30, verbose_name='Rol')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar')),
                ('employee_number', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Número de empleado')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='Fecha de contratación')),
                ('is_available', models.BooleanField(default=True, help_text='Indica si el empleado está disponible para asignaciones', verbose_name='Disponible')),
                ('bio', models.TextField(blank=True, help_text='Información adicional del empleado', verbose_name='Biografía')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.department', verbose_name='Departamento')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
            },
        ),
    ]
