# Generated by Django 6.0 on 2025-12-23 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('director', 'Director/a'), ('jefe_recepcion', 'Jefe/a de Recepción'), ('recepcionista', 'Recepcionista'), ('jefe_limpieza', 'Jefe/a de Limpieza'), ('camarero_piso', 'Camarero/a de Piso'), ('jefe_mantenimiento', 'Jefe/a de Mantenimiento'), ('mantenimiento', 'Personal de Mantenimiento'), ('rrhh', 'Recursos Humanos')], help_text='Rol del empleado en el hotel', max_length=30, verbose_name='Rol'),
        ),
    ]
