# Generated by Django 6.0 on 2026-02-09 10:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0002_alter_employee_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="code",
            field=models.CharField(
                help_text="3 uppercase letters code (e.g. : DIR, REC, LIM)",
                max_length=3,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_code",
                        message="Code must be exactly 3 uppercase letters",
                        regex="^[A-Z]{3}$",
                    )
                ],
                verbose_name="Code",
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="color",
            field=models.CharField(
                choices=[
                    ("#3B82F6", "Blue"),
                    ("#10B981", "Green"),
                    ("#F59E0B", "Yellow"),
                    ("#EF4444", "Red"),
                    ("#8B5CF6", "Purple"),
                    ("#EC4899", "Pink"),
                    ("#F97316", "Orange"),
                    ("#06B6D4", "Cyan"),
                    ("#6366F1", "Indigo"),
                    ("#84CC16", "Lima"),
                    ("#059669", "Emerald"),
                    ("#6B7280", "Grey"),
                ],
                default="#3B82F6",
                max_length=7,
                verbose_name="Color",
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="department",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="department",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
        migrations.AlterField(
            model_name="department",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="department",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="employees.department",
                verbose_name="Departament",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="employee",
            name="role",
            field=models.CharField(
                choices=[
                    ("director", "Director"),
                    ("reception_manager", "Reception Manager"),
                    ("receptionist", "Recepcionist"),
                    ("housekeeping_manager", "Housekeeping Manager"),
                    ("housekeeper", "Housekeeper"),
                    ("maitenance_manager", "Maitenance Manager"),
                    ("maitenance_staff", "Maitenance Staff"),
                    ("rrhh", "Human Resources"),
                ],
                help_text="Rol del empleado en el hotel",
                max_length=30,
                verbose_name="Rol",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employee",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
