# Generated by Django 6.0 on 2026-02-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0003_alter_department_code_alter_department_color_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employee",
            options={
                "verbose_name": "Employee Profile",
                "verbose_name_plural": "Employee Profiles",
            },
        ),
        migrations.AlterField(
            model_name="employee",
            name="bio",
            field=models.TextField(
                blank=True,
                help_text="Additional employee information",
                verbose_name="Biography",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="employee_number",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                unique=True,
                verbose_name="Employee number",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="hire_date",
            field=models.DateField(blank=True, null=True, verbose_name="Hire date"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="is_available",
            field=models.BooleanField(
                default=True,
                help_text="Indicates if the employee is available for assignments",
                verbose_name="Available",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="phone",
            field=models.CharField(blank=True, max_length=20, verbose_name="Phone"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="role",
            field=models.CharField(
                choices=[
                    ("director", "Director"),
                    ("reception_manager", "Reception Manager"),
                    ("receptionist", "Recepcionist"),
                    ("housekeeping_manager", "Housekeeping Manager"),
                    ("housekeeper", "Housekeeper"),
                    ("maitenance_manager", "Maitenance Manager"),
                    ("maitenance_staff", "Maitenance Staff"),
                    ("rrhh", "Human Resources"),
                ],
                help_text="Employee role in the hotel",
                max_length=30,
                verbose_name="Role",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Last updated"),
        ),
    ]
