# Generated by Django 6.0 on 2026-02-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0004_alter_employee_options_alter_employee_bio_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="role",
            field=models.CharField(
                choices=[
                    ("director", "Director"),
                    ("reception_manager", "Reception Manager"),
                    ("receptionist", "Recepcionist"),
                    ("housekeeping_manager", "Housekeeping Manager"),
                    ("housekeeper", "Housekeeper"),
                    ("maintenance_manager", "Maintenance Manager"),
                    ("maintenance_staff", "Maintenance Staff"),
                    ("rrhh", "Human Resources"),
                ],
                help_text="Employee role in the hotel",
                max_length=30,
                verbose_name="Role",
            ),
        ),
    ]
