# Generated by Django 6.0 on 2026-02-20 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0005_alter_employee_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="address",
            field=models.TextField(blank=True, verbose_name="Address"),
        ),
        migrations.AddField(
            model_name="employee",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="dni",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=20,
                null=True,
                unique=True,
                verbose_name="DNI",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("F", "Female"), ("M", "Male"), ("NTS", "Prefer not to say")],
                max_length=10,
                null=True,
                verbose_name="Gender",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="salary",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
    ]
