# Generated by Django 6.0 on 2026-01-03 21:29

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_alter_employee_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, unique=True, verbose_name='Número')),
                ('floor', models.PositiveIntegerField(verbose_name='Piso')),
                ('status', models.CharField(choices=[('clean', 'Limpia'), ('dirty', 'Sucia'), ('inspected', 'Inspeccionada'), ('maintenance', 'En mantenimiento'), ('out_of_order', 'Fuera de servicio')], default='dirty', max_length=20, verbose_name='Estado de limpieza')),
                ('occupancy', models.CharField(choices=[('vacant', 'Vacante'), ('occupied', 'Ocupada'), ('reserved', 'Reservada')], default='vacant', max_length=20, verbose_name='Estado de ocupación')),
                ('last_cleaned', models.DateTimeField(blank=True, null=True, verbose_name='Última limpieza')),
                ('last_inspected', models.DateTimeField(blank=True, null=True, verbose_name='Última inspección')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('capacity', models.PositiveIntegerField(help_text='Número máximo de huéspedes', verbose_name='Capacidad')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('amenities', models.TextField(blank=True, help_text='Lista de amenidades incluidas', verbose_name='Comodidades')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', max_length=10, verbose_name='Prioridad')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('assigned', 'Asignada'), ('in_progress', 'En progreso'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], default='pending', max_length=20, verbose_name='Estado')),
                ('resolution', models.TextField(blank=True, verbose_name='Resolución')),
                ('photos', models.ImageField(blank=True, null=True, upload_to='maintenance/', verbose_name='Fotos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('assigned_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de asignación')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de resolución')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_maintenance', to='employees.employee', verbose_name='Asignado a')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_maintenance', to=settings.AUTH_USER_MODEL, verbose_name='Reportado por')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to='rooms.room', verbose_name='Habitación')),
            ],
            options={
                'verbose_name': 'Solicitud de Mantenimiento',
                'verbose_name_plural': 'Solicitudes de Mantenimiento',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CleaningTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleaning_type', models.CharField(choices=[('checkout', 'Salida'), ('stay_over', 'Cliente'), ('deep_cleaning', 'Limpieza profunda')], default='checkout', max_length=20, verbose_name='Tipo de limpieza')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En progreso'), ('completed', 'Completada'), ('verified', 'Verificada')], default='pending', max_length=20, verbose_name='Estado')),
                ('priority', models.PositiveIntegerField(default=1, help_text='1 = Alta, 5 = Baja', verbose_name='Prioridad')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de verificación')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('photos', models.ImageField(blank=True, null=True, upload_to='cleaning_tasks/', verbose_name='Fotos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleaning_tasks', to='employees.employee', verbose_name='Asignado a')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_cleanings', to=settings.AUTH_USER_MODEL, verbose_name='Verificado por')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleaning_tasks', to='rooms.room', verbose_name='Habitación')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rooms.roomtype', verbose_name='Tipo de habitación'),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_number', models.CharField(editable=False, help_text='Se genera automáticamente', max_length=20, unique=True, verbose_name='Número de reserva')),
                ('check_in_date', models.DateField(verbose_name='Fecha de entrada')),
                ('check_out_date', models.DateField(verbose_name='Fecha de salida')),
                ('actual_check_in', models.DateTimeField(blank=True, help_text='Fecha y hora real de entrada', null=True, verbose_name='Check-in real')),
                ('actual_check_out', models.DateTimeField(blank=True, help_text='Fecha y hora real de salida', null=True, verbose_name='Check-out real')),
                ('guest_first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('guest_last_name', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('guest_email', models.EmailField(help_text='Email del huésped', max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('guest_phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('guest_dni', models.CharField(blank=True, help_text='Documento de identidad', max_length=20, verbose_name='DNI/Pasaporte')),
                ('guest_nationality', models.CharField(blank=True, max_length=50, verbose_name='Nacionalidad')),
                ('guest_address', models.TextField(blank=True, verbose_name='Dirección')),
                ('adults', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Adultos')),
                ('children', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Niños')),
                ('special_requests', models.TextField(blank=True, help_text='Peticiones del huésped', verbose_name='Solicitudes especiales')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmada'), ('pending_checkin', 'Checkin pendiente'), ('checked_in', 'En estancia'), ('pending_checkout', 'Checkout pendiente'), ('checked_out', 'Finalizada'), ('cancelled', 'Cancelada'), ('no_show', 'No se presentó')], default='pending', max_length=20, verbose_name='Estado')),
                ('room_rate', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Tarifa por noche')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Importe total')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Importe pagado')),
                ('payment_status', models.CharField(choices=[('unpaid', 'Sin pagar'), ('partial', 'Pago parcial'), ('paid', 'Pagado'), ('refunded', 'Reembolsado')], default='unpaid', max_length=20, verbose_name='Estado del pago')),
                ('internal_notes', models.TextField(blank=True, help_text='Notas del personal (no visibles para el huésped)', verbose_name='Notas internas')),
                ('cancellation_reason', models.TextField(blank=True, verbose_name='Motivo de cancelación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('checked_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkins_processed', to='employees.employee', verbose_name='Check-in realizado por')),
                ('checked_out_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkouts_processed', to='employees.employee', verbose_name='Check-out realizado por')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reservations', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='rooms.room', verbose_name='Habitación')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-check_in_date', '-created_at'],
                'indexes': [models.Index(fields=['check_in_date', 'check_out_date'], name='rooms_reser_check_i_0a257f_idx'), models.Index(fields=['room', 'status'], name='rooms_reser_room_id_65b3d9_idx'), models.Index(fields=['guest_email'], name='rooms_reser_guest_e_b8c4e5_idx'), models.Index(fields=['reservation_number'], name='rooms_reser_reserva_db62f5_idx')],
            },
        ),
    ]
