# Generated by Django 6.0 on 2025-12-10 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, unique=True, verbose_name='Número')),
                ('floor', models.PositiveIntegerField(verbose_name='Piso')),
                ('status', models.CharField(choices=[('clean', 'Limpia'), ('dirty', 'Sucia'), ('inspected', 'Inspeccionada'), ('maintenance', 'En mantenimiento'), ('out_of_order', 'Fuera de servicio')], default='dirty', max_length=20, verbose_name='Estado de limpieza')),
                ('occupancy', models.CharField(choices=[('vacant', 'Vacante'), ('occupied', 'Ocupada'), ('reserved', 'Reservada')], default='vacant', max_length=20, verbose_name='Estado de ocupación')),
                ('last_cleaned', models.DateTimeField(blank=True, null=True, verbose_name='Última limpieza')),
                ('last_inspected', models.DateTimeField(blank=True, null=True, verbose_name='Última inspección')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('capacity', models.PositiveIntegerField(help_text='Número máximo de huéspedes', verbose_name='Capacidad')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio base')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('amenities', models.TextField(blank=True, help_text='Lista de amenidades incluidas', verbose_name='Comodidades')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', max_length=10, verbose_name='Prioridad')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('assigned', 'Asignada'), ('in_progress', 'En progreso'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], default='pending', max_length=20, verbose_name='Estado')),
                ('resolution', models.TextField(blank=True, verbose_name='Resolución')),
                ('photos', models.ImageField(blank=True, null=True, upload_to='maintenance/', verbose_name='Fotos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('assigned_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de asignación')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de resolución')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_maintenance', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_maintenance', to=settings.AUTH_USER_MODEL, verbose_name='Reportado por')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to='rooms.room', verbose_name='Habitación')),
            ],
        ),
        migrations.CreateModel(
            name='CleaningTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleaning_type', models.CharField(choices=[('checkout', 'Salida'), ('stay_over', 'Estadía'), ('deep_cleaning', 'Limpieza profunda')], default='checkout', max_length=20, verbose_name='Tipo de limpieza')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En progreso'), ('completed', 'Completada'), ('verified', 'Verificada')], default='pending', max_length=20, verbose_name='Estado')),
                ('priority', models.PositiveIntegerField(default=1, help_text='1 = Alta, 5 = Baja', verbose_name='Prioridad')),
                ('scheduled_time', models.DateTimeField(verbose_name='Hora programada')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Hora de inicio')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Hora de finalización')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de verificación')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('photos', models.ImageField(blank=True, null=True, upload_to='cleaning_tasks/', verbose_name='Fotos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleaning_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_cleanings', to=settings.AUTH_USER_MODEL, verbose_name='Verificado por')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleaning_tasks', to='rooms.room', verbose_name='Habitación')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rooms.roomtype', verbose_name='Tipo de habitación'),
        ),
    ]
