# Generated by Django 6.0 on 2026-01-04 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancetask',
            name='started_at',
        ),
        migrations.AddField(
            model_name='cleaningtask',
            name='completed_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Limpieza terminada'),
        ),
    ]
