# Generated by Django 6.0 on 2025-12-14 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cleaningtask',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='cleaningtask',
            name='scheduled_time',
        ),
        migrations.RemoveField(
            model_name='cleaningtask',
            name='started_at',
        ),
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='resolved_at',
        ),
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='started_at',
        ),
        migrations.RemoveField(
            model_name='roomtype',
            name='base_price',
        ),
        migrations.AlterField(
            model_name='cleaningtask',
            name='cleaning_type',
            field=models.CharField(choices=[('checkout', 'Salida'), ('stay_over', 'Cliente'), ('deep_cleaning', 'Limpieza profunda')], default='checkout', max_length=20, verbose_name='Tipo de limpieza'),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre del huésped')),
                ('check_in', models.DateField(verbose_name='Fecha de entrada')),
                ('check_out', models.DateField(verbose_name='Fecha de salida')),
                ('actual_check_in', models.DateTimeField(blank=True, null=True, verbose_name='Check-in real')),
                ('actual_check_out', models.DateTimeField(blank=True, null=True, verbose_name='Check-out real')),
                ('nights', models.PositiveIntegerField(verbose_name='Noches')),
                ('status', models.CharField(choices=[('confirmed', 'Confirmada'), ('checked_in', 'En estancia'), ('checked_out', 'Finalizada'), ('cancelled', 'Cancelada')], default='confirmed', max_length=20)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='rooms.room')),
            ],
        ),
    ]
