# Generated by Django 6.0 on 2026-02-15 17:06

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0005_alter_employee_role"),
        ("rooms", "0002_remove_maintenancetask_started_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cleaningtask",
            options={
                "ordering": ["-created_at"],
                "verbose_name": ("Cleaning Task",),
                "verbose_name_plural": ("Cleaning Tasks",),
            },
        ),
        migrations.AlterModelOptions(
            name="maintenancetask",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Maintenance Request",
                "verbose_name_plural": "Maintenance Requests",
            },
        ),
        migrations.AlterModelOptions(
            name="reservation",
            options={
                "ordering": ["-check_in_date", "-created_at"],
                "verbose_name": "Reservation",
                "verbose_name_plural": "Reservations",
            },
        ),
        migrations.AlterModelOptions(
            name="room",
            options={
                "ordering": ["floor", "number"],
                "verbose_name": "Room",
                "verbose_name_plural": "Rooms",
            },
        ),
        migrations.AlterModelOptions(
            name="roomtype",
            options={"verbose_name": "Room Type", "verbose_name_plural": "Room Types"},
        ),
        migrations.AlterField(
            model_name="cleaningtask",
            name="assigned_to",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cleaning_tasks",
                to="employees.employee",
                verbose_name="Assigned to",
            ),
        ),
        migrations.AlterField(
            model_name="cleaningtask",
            name="cleaning_type",
            field=models.CharField(
                choices=[
                    ("checkout", "Checkout"),
                    ("stay_over", "Stay over"),
                    ("deep_cleaning", "Deep cleaning"),
                ],
                default="checkout",
                max_length=20,
                verbose_name="Cleaning type",
            ),
        ),
        migrations.AlterField(
            model_name="cleaningtask",
            name="completed_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Completed at"),
        ),
        migrations.AlterField(
            model_name="cleaningtask",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="cleaningtask",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Notes"),
        ),
        migrations.AlterField(
            model_name="cleaningtask",
            name="photos",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="cleaning_tasks/",
                verbose_name="Photos",
            ),
        ),
        migrations.AlterField(
            model_name="cleaningtask",
            name="priority",
            field=models.PositiveIntegerField(
                default=1, help_text="1 = Alta, 5 = Baja", verbose_name="Priority"
            ),
        ),
        migrations.AlterField(
            model_name="cleaningtask",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cleaning_tasks",
                to="rooms.room",
                verbose_name="Room",
            ),
        ),
        migrations.AlterField(
            model_name="cleaningtask",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("in_progress", "In progress"),
                    ("completed", "Completed"),
                    ("verified", "Verified"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="cleaningtask",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Last updated"),
        ),
        migrations.AlterField(
            model_name="cleaningtask",
            name="verified_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Verification date"
            ),
        ),
        migrations.AlterField(
            model_name="cleaningtask",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_cleanings",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Verified by",
            ),
        ),
        migrations.AlterField(
            model_name="maintenancetask",
            name="assigned_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Assigned to"
            ),
        ),
        migrations.AlterField(
            model_name="maintenancetask",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_maintenance",
                to="employees.employee",
                verbose_name="Assigned to",
            ),
        ),
        migrations.AlterField(
            model_name="maintenancetask",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="maintenancetask",
            name="description",
            field=models.TextField(verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="maintenancetask",
            name="photos",
            field=models.ImageField(
                blank=True, null=True, upload_to="maintenance/", verbose_name="Photos"
            ),
        ),
        migrations.AlterField(
            model_name="maintenancetask",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("urgent", "Urgent"),
                ],
                default="medium",
                max_length=10,
                verbose_name="Priority",
            ),
        ),
        migrations.AlterField(
            model_name="maintenancetask",
            name="reported_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reported_maintenance",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Reported by",
            ),
        ),
        migrations.AlterField(
            model_name="maintenancetask",
            name="resolution",
            field=models.TextField(blank=True, verbose_name="Resolution"),
        ),
        migrations.AlterField(
            model_name="maintenancetask",
            name="resolved_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Resolution date"
            ),
        ),
        migrations.AlterField(
            model_name="maintenancetask",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="maintenance_requests",
                to="rooms.room",
                verbose_name="Room",
            ),
        ),
        migrations.AlterField(
            model_name="maintenancetask",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("assigned", "Assigned"),
                    ("in_progress", "In progress"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="maintenancetask",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="maintenancetask",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Last updated"),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="actual_check_in",
            field=models.DateTimeField(
                blank=True,
                help_text="Actual check-in date and time",
                null=True,
                verbose_name="Actual check-in",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="actual_check_out",
            field=models.DateTimeField(
                blank=True,
                help_text="Actual check-out date and time",
                null=True,
                verbose_name="Actual check-out",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="adults",
            field=models.PositiveIntegerField(
                default=1,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Adults",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="cancellation_reason",
            field=models.TextField(blank=True, verbose_name="Cancellation reason"),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="check_in_date",
            field=models.DateField(verbose_name="Check-in date"),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="check_out_date",
            field=models.DateField(verbose_name="Check-out date"),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="checked_in_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="checkins_processed",
                to="employees.employee",
                verbose_name="Checked in by",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="checked_out_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="checkouts_processed",
                to="employees.employee",
                verbose_name="Checked out by",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="children",
            field=models.PositiveIntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Children",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_reservations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="guest_address",
            field=models.TextField(blank=True, verbose_name="Address"),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="guest_dni",
            field=models.CharField(
                blank=True,
                help_text="Identity document",
                max_length=20,
                verbose_name="ID/Passport",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="guest_email",
            field=models.EmailField(
                help_text="Guest's email", max_length=254, verbose_name="Email"
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="guest_first_name",
            field=models.CharField(max_length=100, verbose_name="First name"),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="guest_last_name",
            field=models.CharField(max_length=100, verbose_name="Last name"),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="guest_nationality",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Nationality"
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="guest_phone",
            field=models.CharField(max_length=20, verbose_name="Phone"),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="internal_notes",
            field=models.TextField(
                blank=True,
                help_text="Staff notes (not visible to guest)",
                verbose_name="Internal notes",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="paid_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Paid amount",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("unpaid", "Unpaid"),
                    ("partial", "Partial payment"),
                    ("paid", "Paid"),
                    ("refunded", "Refunded"),
                ],
                default="unpaid",
                max_length=20,
                verbose_name="Payment status",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="reservation_number",
            field=models.CharField(
                editable=False,
                help_text="Auto-generated",
                max_length=20,
                unique=True,
                verbose_name="Reservation number",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reservations",
                to="rooms.room",
                verbose_name="Room",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="room_rate",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="Room rate per night",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="special_requests",
            field=models.TextField(
                blank=True,
                help_text="Guest's requests",
                verbose_name="Special requests",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("pending_checkin", "Pending check-in"),
                    ("checked_in", "Checked in"),
                    ("pending_checkout", "Pending check-out"),
                    ("checked_out", "Checked out"),
                    ("cancelled", "Canceled"),
                    ("no_show", "No show"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="total_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Total amount",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Last updated"),
        ),
        migrations.AlterField(
            model_name="room",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="room",
            name="floor",
            field=models.PositiveIntegerField(verbose_name="Floor"),
        ),
        migrations.AlterField(
            model_name="room",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
        migrations.AlterField(
            model_name="room",
            name="last_cleaned",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Last cleaned"
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="last_inspected",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Last inspected"
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Notes"),
        ),
        migrations.AlterField(
            model_name="room",
            name="number",
            field=models.CharField(max_length=10, unique=True, verbose_name="Number"),
        ),
        migrations.AlterField(
            model_name="room",
            name="occupancy",
            field=models.CharField(
                choices=[
                    ("vacant", "Vacant"),
                    ("occupied", "Occupied"),
                    ("reserved", "Reserved"),
                ],
                default="vacant",
                max_length=20,
                verbose_name="Occupancy status",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="rooms.roomtype",
                verbose_name="Room type",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="status",
            field=models.CharField(
                choices=[
                    ("clean", "Clean"),
                    ("dirty", "Dirty"),
                    ("inspected", "Inspected"),
                    ("maintenance", "Under maintenance"),
                    ("out_of_order", "Out of order"),
                ],
                default="dirty",
                max_length=20,
                verbose_name="Cleaning status",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Last updated"),
        ),
        migrations.AlterField(
            model_name="roomtype",
            name="amenities",
            field=models.TextField(
                blank=True, help_text="Amenities included", verbose_name="Amenities"
            ),
        ),
        migrations.AlterField(
            model_name="roomtype",
            name="capacity",
            field=models.PositiveIntegerField(
                help_text="Maximum capacity number", verbose_name="Capacity"
            ),
        ),
        migrations.AlterField(
            model_name="roomtype",
            name="code",
            field=models.CharField(max_length=10, unique=True, verbose_name="Code"),
        ),
        migrations.AlterField(
            model_name="roomtype",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="roomtype",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
        migrations.AlterField(
            model_name="roomtype",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Name"),
        ),
        migrations.AddConstraint(
            model_name="reservation",
            constraint=models.CheckConstraint(
                condition=models.Q(("check_out_date__gt", models.F("check_in_date"))),
                name="valid_reservation_date_range",
            ),
        ),
    ]
