# Generated by Django 6.0 on 2025-12-23 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_role'),
        ('rooms', '0002_rename_maintenancerequest_maintenancetask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaningtask',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleaning_tasks', to='employees.employee', verbose_name='Asignado a'),
        ),
        migrations.AlterField(
            model_name='maintenancetask',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_maintenance', to='employees.employee', verbose_name='Asignado a'),
        ),
    ]
