# Generated by Django 6.0 on 2025-12-18 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_remove_cleaningtask_completed_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenancerequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Solicitud de Mantenimiento', 'verbose_name_plural': 'Solicitudes de Mantenimiento'},
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de resolución'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de inicio'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
    ]
