# Generated by Django 6.0 on 2026-02-20 11:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0003_alter_cleaningtask_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cleaningtask",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Cleaning Task",
                "verbose_name_plural": "Cleaning Tasks",
            },
        ),
    ]
